# -*- coding: utf-8 -*-
"""train_retention_fixed

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/119YtysQxdMUmp6BaxmCETPbqR6QASZ06
"""

# ==========================================
# Employee Retention Model (Fixed & Balanced)
# ==========================================

import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.metrics import classification_report, confusion_matrix

# ------------------------------
# 1️⃣ Create synthetic dataset
# ------------------------------
np.random.seed(42)
n = 2500  # more diverse samples

df = pd.DataFrame({
    "Age": np.random.randint(22, 60, n),
    "MonthlyIncome": np.random.randint(2000, 20000, n),
    "JobSatisfaction": np.random.randint(1, 5, n),
    "OverTime": np.random.choice(["Yes", "No"], n),
    "YearsAtCompany": np.random.randint(0, 20, n),
    "JobRole": np.random.choice(["Manager", "Sales Executive", "Human Resources", "Research Scientist"], n),
    "Department": np.random.choice(["Human Resources", "Sales", "Research & Development"], n),
    "Gender": np.random.choice(["Male", "Female"], n),
    "BusinessTravel": np.random.choice(["Non-Travel", "Travel_Rarely", "Travel_Frequently"], n),
    "EducationField": np.random.choice(["Life Sciences", "Medical", "Marketing", "Technical Degree", "Other"], n),
    "DistanceFromHome": np.random.randint(1, 30, n)
})

# ------------------------------
# 2️⃣ Improved Attrition logic
# ------------------------------
# Weighted conditions to make model learn richer patterns
conditions = (
    (df["MonthlyIncome"] < 7000) |
    ((df["JobSatisfaction"] <= 2) & (df["OverTime"] == "Yes")) |
    ((df["YearsAtCompany"] < 3) & (df["BusinessTravel"] == "Travel_Frequently")) |
    ((df["DistanceFromHome"] > 20) & (df["OverTime"] == "Yes")) |
    ((df["JobRole"] == "Sales Executive") & (df["JobSatisfaction"] <= 2))
)
df["Attrition"] = conditions.astype(int)

print("✅ Dataset Created | Attrition Distribution:")
print(df["Attrition"].value_counts(normalize=True))

# ------------------------------
# 3️⃣ Split features and target
# ------------------------------
X = df.drop(columns=["Attrition"])
y = df["Attrition"]

# ------------------------------
# 4️⃣ Preprocessing pipeline
# ------------------------------
categorical_cols = X.select_dtypes(include="object").columns
numeric_cols = X.select_dtypes(exclude="object").columns

preprocessor = ColumnTransformer([
    ("categorical", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
    ("numeric", "passthrough", numeric_cols)
])

# ------------------------------
# 5️⃣ Balance dataset using SMOTE
# ------------------------------
from imblearn.pipeline import Pipeline as ImbPipeline

model_pipeline = ImbPipeline([
    ("preprocessor", preprocessor),
    ("smote", SMOTE(random_state=42)),
    ("classifier", RandomForestClassifier(
        n_estimators=200,
        max_depth=10,
        class_weight="balanced",
        random_state=42
    ))
])

# ------------------------------
# 6️⃣ Train/test split and train model
# ------------------------------
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model_pipeline.fit(X_train, y_train)

# ------------------------------
# 7️⃣ Evaluate results
# ------------------------------
y_pred = model_pipeline.predict(X_test)
print("\n🎯 Model Evaluation Results:")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# ------------------------------
# 8️⃣ Save final model
# ------------------------------
with open("retention_model_light.pkl", "wb") as f:
    pickle.dump(model_pipeline, f)

print("\n💾 New model saved as retention_model_light.pkl")


from google.colab import files
files.download('retention_model_light.pkl')

